"""Parity gates for the Rust ADES writer/parser (bead personal-cmy.20 slices
B/C) against the frozen legacy fixture generated by the untouched legacy
checkout (no Rust work) via
``.legacy-venv/bin/python migration/scripts/generate_ades_parity_fixture.py``.

The Rust-dispatched public ``ADES_to_string`` / ``ADES_string_to_tables`` must
reproduce the legacy outputs byte-for-byte: writer strings, parsed observation
columns, parsed ObsContexts, and error messages."""

import json
import math
from dataclasses import asdict
from pathlib import Path

import pytest

from ...time import Timestamp
from ..ades import (
    ADES_string_to_tables,
    ADES_to_string,
    ADESObservations,
    ObsContext,
    ObservatoryObsContext,
    SoftwareObsContext,
    SubmitterObsContext,
    TelescopeObsContext,
)

FIXTURE_PATH = (
    Path(__file__).resolve().parents[4]
    / "migration"
    / "artifacts"
    / "ades_parity_fixture_2026-07-05.json"
)


@pytest.fixture(scope="module")
def fixture():
    return json.loads(FIXTURE_PATH.read_text())


def build_contexts(spec: dict) -> dict[str, ObsContext]:
    contexts = {}
    for code, entry in spec.items():
        contexts[code] = ObsContext(
            observatory=ObservatoryObsContext(**entry["observatory"]),
            submitter=SubmitterObsContext(**entry["submitter"]),
            observers=list(entry["observers"]),
            measurers=list(entry["measurers"]),
            telescope=TelescopeObsContext(**entry["telescope"]),
            software=(
                SoftwareObsContext(**entry["software"])
                if entry.get("software")
                else None
            ),
            fundingSource=entry.get("fundingSource"),
            comments=list(entry["comments"]) if entry.get("comments") else None,
        )
    return contexts


def observations_from_flat(flat: dict) -> ADESObservations:
    kwargs = {column: values for column, values in flat.items() if column != "obsTime"}
    kwargs["obsTime"] = Timestamp.from_kwargs(
        days=flat["obsTime"]["days"],
        nanos=flat["obsTime"]["nanos"],
        scale=flat["obsTime"]["scale"],
    )
    return ADESObservations.from_kwargs(**kwargs)


def assert_flat_equal(observations: ADESObservations, flat: dict, label: str):
    assert observations.obsTime.days.to_pylist() == flat["obsTime"]["days"], label
    assert observations.obsTime.nanos.to_pylist() == flat["obsTime"]["nanos"], label
    assert observations.obsTime.scale == flat["obsTime"]["scale"], label
    for column, expected in flat.items():
        if column == "obsTime":
            continue
        actual = observations.table.column(column).to_pylist()
        assert len(actual) == len(expected), f"{label}:{column}"
        for row, (a, b) in enumerate(zip(actual, expected)):
            if (
                isinstance(a, float)
                and isinstance(b, float)
                and math.isnan(a)
                and math.isnan(b)
            ):
                continue
            assert a == b, f"{label}:{column}[{row}]: {a!r} != {b!r}"


def test_fixture_exists():
    assert FIXTURE_PATH.exists(), (
        "ADES parity fixture missing; generate it with the legacy interpreter: "
        ".legacy-venv/bin/python migration/scripts/generate_ades_parity_fixture.py"
    )


def test_writer_matches_legacy_fixture(fixture):
    contexts = build_contexts(fixture["context_spec"])
    for panel in fixture["panels"]:
        observations = observations_from_flat(panel["observations"])
        kwargs = dict(panel["options"]) if panel["options"] else {}
        actual = ADES_to_string(observations, contexts, **kwargs)
        assert actual == panel["ades_string"], panel["name"]


def test_parser_matches_legacy_fixture(fixture):
    for panel in fixture["panels"] + fixture["raw_strings"]:
        if "parse_error_type" in panel["parsed"]:
            # Legacy writes "nan" for missing values in precision-formatted
            # columns and then fails quivr validation when parsing those
            # files back; the Rust-dispatched parser must fail identically.
            # Documented deviation: legacy validates each parsed block
            # separately while the Rust path validates the concatenated
            # table, so the reported failure *count/index* can differ; the
            # exception type, column, and validator must match exactly.
            with pytest.raises(Exception) as exc_info:
                ADES_string_to_tables(panel["ades_string"])
            assert (
                type(exc_info.value).__name__ == panel["parsed"]["parse_error_type"]
            ), panel["name"]
            expected_prefix = panel["parsed"]["parse_error_message"].split(
                " failed on "
            )[0]
            assert str(exc_info.value).startswith(expected_prefix), panel["name"]
            continue
        parsed_contexts, parsed_observations = ADES_string_to_tables(
            panel["ades_string"]
        )
        assert_flat_equal(
            parsed_observations, panel["parsed"]["observations"], panel["name"]
        )
        actual_contexts = {
            code: asdict(context) for code, context in parsed_contexts.items()
        }
        assert actual_contexts == panel["parsed"]["contexts"], panel["name"]


def test_fused_ades_native_timing(fixture):
    from adam_core import _rust_native
    from adam_core.observations.arrow_bridge import observations_to_ipc

    panel = fixture["panels"][0]
    observations = observations_from_flat(panel["observations"])
    contexts = build_contexts(fixture["context_spec"])
    contexts_json = {
        code: json.dumps(asdict(context)) for code, context in contexts.items()
    }
    options = panel.get("options") or {}
    seconds_precision = int(options.get("seconds_precision", 3))
    columns_precision = options.get(
        "columns_precision",
        {
            "ra": 9,
            "dec": 9,
            "rmsRACosDec": 5,
            "rmsDec": 5,
            "rmsCorr": 8,
            "mag": 4,
            "rmsMag": 4,
            "exp": 2,
            "logSNR": 2,
            "seeing": 2,
        },
    )
    writer_samples = _rust_native.benchmark_ades_to_string_fused_ipc(
        observations_to_ipc(observations),
        contexts_json,
        seconds_precision,
        columns_precision,
        2,
        2,
        1,
    )
    parser_samples = _rust_native.benchmark_ades_string_to_tables_fused(
        panel["ades_string"], 2, 2, 1
    )
    assert all(sample > 0.0 for trial in writer_samples for sample in trial)
    assert all(sample > 0.0 for trial in parser_samples for sample in trial)


def test_writer_empty_observations():
    contexts = build_contexts(
        {
            "695": {
                "observatory": {"mpcCode": "695"},
                "submitter": {"name": "J. Doe"},
                "observers": ["J. Doe"],
                "measurers": ["J. Doe"],
                "telescope": {
                    "design": "Reflector",
                    "aperture": 1.0,
                    "detector": "CCD",
                },
            }
        }
    )
    assert ADES_to_string(ADESObservations.empty(), contexts) == "# version=2022\n"


def test_error_messages_match_legacy_fixture(fixture):
    contexts = build_contexts(
        {
            code: entry
            for code, entry in fixture["context_spec"].items()
            if code != "V00"
        }
    )
    # Panels are seeded, so seed 11/n 32 from the generator is reproduced by
    # reusing a stored panel that contains V00 rows instead.
    panel = fixture["panels"][0]
    observations = observations_from_flat(panel["observations"])
    assert "V00" in observations.stn.to_pylist()
    with pytest.raises(ValueError) as exc_info:
        ADES_to_string(observations, contexts)
    assert str(exc_info.value) == fixture["errors"]["missing_context"]

    no_ids = ADESObservations.from_kwargs(
        obsTime=Timestamp.from_mjd([60434.0], scale="utc"),
        ra=[10.0],
        dec=[-5.0],
        stn=["695"],
        mode=["CCD"],
        astCat=["Gaia2"],
    )
    with pytest.raises(ValueError) as exc_info:
        ADES_to_string(no_ids, build_contexts(fixture["context_spec"]))
    assert str(exc_info.value) == fixture["errors"]["missing_ids"]
