import pyarrow as pa
import quivr as qv

from ..time import Timestamp


class RotationPeriodObservations(qv.Table):
    time = Timestamp.as_column()
    mag = qv.Float64Column()
    mag_sigma = qv.Float64Column(nullable=True)
    predicted_mag_v = qv.Float64Column(nullable=True)
    filter = qv.LargeStringColumn(nullable=True)
    session_id = qv.LargeStringColumn(nullable=True)
    r_au = qv.Float64Column()
    delta_au = qv.Float64Column()
    phase_angle_deg = qv.Float64Column()


class RotationPeriodResult(qv.Table):
    period_days = qv.Float64Column()
    period_hours = qv.Float64Column()
    frequency_cycles_per_day = qv.Float64Column()
    primary_method = qv.LargeStringColumn()
    paper_profile = qv.LargeStringColumn()
    period_verdict = qv.LargeStringColumn()
    reliability_code = qv.LargeStringColumn()
    confidence_flags = qv.LargeListColumn(pa.large_string(), nullable=True)
    insufficiency_reasons = qv.LargeListColumn(pa.large_string(), nullable=True)
    is_valid = qv.BooleanColumn()
    is_reliable = qv.BooleanColumn()
    period_lower_days = qv.Float64Column(nullable=True)
    period_upper_days = qv.Float64Column(nullable=True)
    relative_period_uncertainty = qv.Float64Column(nullable=True)
    alternate_period_days = qv.LargeListColumn(pa.float64(), nullable=True)
    fourier_period_days = qv.Float64Column(nullable=True)
    fourier_order = qv.Int64Column(nullable=True)
    fourier_sigma_threshold = qv.Float64Column(nullable=True)
    fourier_phase_c1 = qv.Float64Column(nullable=True)
    fourier_phase_c2 = qv.Float64Column(nullable=True)
    residual_sigma_mag = qv.Float64Column(nullable=True)
    fourier_is_valid = qv.BooleanColumn(nullable=True)
    fourier_is_reliable = qv.BooleanColumn(nullable=True)
    fourier_alternate_period_days = qv.LargeListColumn(pa.float64(), nullable=True)
    lsm_period_days = qv.Float64Column(nullable=True)
    lsm_power = qv.Float64Column(nullable=True)
    lsm_power_gap = qv.Float64Column(nullable=True)
    lsm_candidate_period_days = qv.LargeListColumn(pa.float64(), nullable=True)
    lsm_candidate_powers = qv.LargeListColumn(pa.float64(), nullable=True)
    lsm_is_reliable = qv.BooleanColumn(nullable=True)
    lsm_false_alarm_probability = qv.Float64Column(nullable=True)
    method_agreement_class = qv.LargeStringColumn(nullable=True)
    decision_margin = qv.Float64Column(nullable=True)
    decision_support_count = qv.Int64Column(nullable=True)
    winner_contains_fourier_primary = qv.BooleanColumn(nullable=True)
    winner_contains_lsm_primary = qv.BooleanColumn(nullable=True)
    family_weight_fourier = qv.Float64Column(nullable=True)
    family_weight_lsm = qv.Float64Column(nullable=True)
    phase_coverage_fraction = qv.Float64Column(nullable=True)
    n_rotations_spanned = qv.Float64Column(nullable=True)
    amplitude_snr = qv.Float64Column(nullable=True)
    n_significant_aliases = qv.Int64Column(nullable=True)
    n_observations = qv.Int64Column()
    n_fit_observations = qv.Int64Column()
    n_clipped = qv.Int64Column()
    n_filters = qv.Int64Column()
    n_sessions = qv.Int64Column()
    used_session_offsets = qv.BooleanColumn()
    is_period_doubled = qv.BooleanColumn()


class GroupedRotationPeriodResults(qv.Table):
    object_id = qv.LargeStringColumn()
    result = RotationPeriodResult.as_column()
