[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "adam_core"
authors = [
  { name = "Kathleen Kiker", email = "kathleen@b612foundation.org" },
  { name = "Alec Koumjian", email = "alec@b612foundation.org" },
  { name = "Joachim Moeyens", email = "moeyensj@uw.edu" },
  { name = "Spencer Nelson", email = "spencer@b612foundation.org" },
  { name = "Nate Tellis", email = "nate@b612foundation.org" },
]
description = "Core libraries for the ADAM platform"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dynamic = ["version"]

dependencies = [
  "astropy",
  "astroquery",
  "healpy",
  "jax",
  "jaxlib",
  "numpy<1.25",
  "pyarrow>=13.0.0",
  # This fork removes errors that occur with true anomaly values 
  "pyoorb@git+https://github.com/B612-Asteroid-Institute/oorb.git@fork",
  "pandas",
  "requests",
  "scipy",
  "spiceypy",
  "quivr>=0.7.1",
  "mpc-obscodes",
  "naif-de440",
  "naif-leapseconds",
  "naif-eop-high-prec",
  "naif-eop-predict",
  "naif-eop-historical",
  "naif-earth-itrf93",
]

[project.urls]
"Homepage" = "https://github.com/b612-asteroid-institute/adam_core"

[tool.hatch.build.targets.sdist]
include = ["/adam_core"]

[tool.hatch.metadata]
# Temporary while pyoorb is referenced via git direct ref
allow-direct-references = true

[tool.hatch.version]
path = "adam_core/__version__.py"

[tool.hatch.envs.dev]
dependencies = [
  "ray",                # TODO: Move to main dependencies once we are ready to move away from concurrent futures
  "black==22.10.0",
  "isort",
  "mypy",
  "pytest",
  "pytest-cov",
  "pytest-benchmark",
  "pytest-doctestplus",
  "pre-commit",
  "ruff",
  "ipython",
]

[tool.hatch.envs.dev.scripts]
check = ["lint", "typecheck", "test"]
fix = ["ruff ./adam_core --fix"]
lint = [
  "ruff ./adam_core",
  "black --check ./adam_core",
  "isort --check-only ./adam_core",
]
format = ["black ./adam_core", "isort ./adam_core"]
typecheck = ["mypy --strict ./adam_core"]
test = ["pytest --benchmark-disable ./adam_core {args}"]
doctest = ["pytest --doctest-plus ./adam_core --doctest-only"]
benchmark = ["pytest --benchmark-only ./adam_core {args}"]
coverage = ["pytest ./adam_core --cov --cov-report xml"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 110
target-version = "py311"
ignore = []
exclude = ["build"]

[tool.hatch.envs.docs]
dependencies = [
  "sphinx",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton",
  "sphinx-toolbox",
  "quivr-sphinx-autodoc",
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton",
  "sphinx-toolbox",
  "quivr-sphinx-autodoc",
]

[tool.hatch.envs.docs.scripts]
make-html = ["make -C docs html"]

clean = ["make -C docs clean"]

open-html = ["open docs/build/html/index.html"]
