[project]
name = "adam_core"
version = "0.1.0"
authors = [
  { name = "Kathleen Kiker", email = "kathleen@b612foundation.org" },
  { name = "Alec Koumjian", email = "alec@b612foundation.org" },
  { name = "Joachim Moeyens", email = "moeyensj@uw.edu" },
  { name = "Spencer Nelson", email = "spencer@b612foundation.org" },
  { name = "Nate Tellis", email = "nate@b612foundation.org" },
]
description = "Core libraries for the ADAM platform"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "astropy",
  "astroquery",
  "healpy",
  "jax",
  "jaxlib",
  "numpy<1.25",
  "pyarrow>=13.0.0",
  "pandas",
  "ray",
  "requests",
  "scipy",
  "spiceypy",
  "quivr@git+https://github.com/moeyensj/quivr@concatenate-empty-attributes",
  "mpc-obscodes",
  "naif-de440",
  "naif-leapseconds",
  "naif-eop-high-prec",
  "naif-eop-predict",
  "naif-eop-historical",
  "naif-earth-itrf93",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
[tool.pdm.build]
includes = ["src/adam_core/"]

[tool.pdm.scripts]
check = {composite = ["lint", "typecheck", "test"]}
format = { composite = ["black ./src/adam_core", "isort ./src/adam_core"]}
lint = { composite = ["ruff check ./src/adam_core", "black --check ./src/adam_core", "isort --check-only ./src/adam_core"] }
fix = "ruff ./src/adam_core --fix"
typecheck = "mypy --strict ./src/adam_core"

test = "pytest --benchmark-disable {args}"
doctest = "pytest --doctest-plus --doctest-only"
benchmark = "pytest --benchmark-only"
coverage = "pytest --cov --cov-report xml"


[project.urls]
"Documentation" = "https://github.com/B612-Asteroid-Institute/adam_core#README.md"
"Issues" = "https://github.com/B612-Asteroid-Institute/adam_core/issues"
"Source" = "https://github.com/B612-Asteroid-Institute/adam_core"


[project.optional-dependencies]
dev = [
    "pdm",
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "ruff",
    "black",
    "isort",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "pytest-doctestplus",
    "pytest-mock",
    "ruff",
    "ipython",
    "adam-pyoorb @ git+https://github.com/B612-Asteroid-Institute/adam-pyoorb.git@main",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 110
target-version = "py311"
lint.ignore = []
exclude = ["build"]

[tool.pytest.ini_options]
# In order for namespace packages to work during tests,
# we need to import from the installed modules instead of local source
addopts = [
    "--pyargs", "adam_core",
]
