"""Parity gates for the fused `orbits_to_sbdb_file` (bead personal-cmy.37.4.5)
against the frozen legacy fixture generated by the untouched legacy checkout
via ``.legacy-venv/bin/python migration/scripts/generate_openspace_sbdb_fixture.py``.

Two gates:

1. The fused Rust CSV must be byte-identical to the retained current-Python
   fallback (astropy epoch strings + pandas ``to_csv``): everything the CSV
   product owns -- epoch rendering, Python float reprs including exponent
   notation, QUOTE_MINIMAL quoting, NaN-as-empty, layout -- is exact.
2. Against the frozen legacy bytes: ``full_name``/``epoch_cal`` columns are
   exact; transform-derived float columns compare within the already-RCA'd
   ``transform_coordinates`` tolerance (the pinned legacy transform differs
   from the parity-gated Rust transform by ULP-scale amounts, e.g. the
   ill-conditioned near-circular eccentricity)."""

import csv
import io
import json
import math
from pathlib import Path

import pytest

from adam_core import _rust_native
from adam_core.coordinates import CartesianCoordinates
from adam_core.coordinates.origin import Origin
from adam_core.orbits import Orbits
from adam_core.orbits.arrow_bridge import orbits_to_ipc
from adam_core.orbits.openspace.assets import orbits_to_sbdb_file
from adam_core.time import Timestamp

FIXTURE_PATH = (
    Path(__file__).resolve().parents[5]
    / "migration"
    / "artifacts"
    / "openspace_sbdb_fixture_2026-07-12.json"
)


@pytest.fixture(scope="module")
def fixture():
    assert FIXTURE_PATH.exists(), (
        "OpenSpace SBDB parity fixture missing; generate it with the legacy "
        "interpreter: .legacy-venv/bin/python "
        "migration/scripts/generate_openspace_sbdb_fixture.py"
    )
    return json.loads(FIXTURE_PATH.read_text())


def orbits_from_flat(flat: dict) -> Orbits:
    return Orbits.from_kwargs(
        orbit_id=flat["orbit_id"],
        object_id=flat["object_id"],
        coordinates=CartesianCoordinates.from_kwargs(
            x=flat["x"],
            y=flat["y"],
            z=flat["z"],
            vx=flat["vx"],
            vy=flat["vy"],
            vz=flat["vz"],
            time=Timestamp.from_kwargs(
                days=flat["days"], nanos=flat["nanos"], scale=flat["scale"]
            ),
            frame=flat["frame"],
            origin=Origin.from_kwargs(code=flat["origin"]),
        ),
    )


def assert_csv_matches_fixture(actual_text: str, expected_text: str, label: str):
    actual = list(csv.reader(io.StringIO(actual_text)))
    expected = list(csv.reader(io.StringIO(expected_text)))
    assert actual[0] == expected[0], label
    assert len(actual) == len(expected), label
    for row, (actual_row, expected_row) in enumerate(zip(actual[1:], expected[1:])):
        # Strings the CSV product owns are exact.
        assert actual_row[0] == expected_row[0], f"{label}:{row}:full_name"
        assert actual_row[1] == expected_row[1], f"{label}:{row}:epoch_cal"
        # Transform-derived floats compare within the governed transform
        # tolerance (ULP-scale legacy-vs-Rust transform deviations).
        for column, (a, b) in enumerate(zip(actual_row[2:], expected_row[2:])):
            if a == b:
                continue
            assert a != "" and b != "", f"{label}:{row}:{column}: nan mismatch"
            fa, fb = float(a), float(b)
            assert math.isclose(
                fa, fb, rel_tol=1e-9, abs_tol=1e-9
            ), f"{label}:{row}:{column}: {a} != {b}"


def test_fused_csv_matches_current_fallback_exactly(fixture, tmp_path):
    from adam_core.orbits.openspace.assets import _orbits_to_sbdb_file_legacy

    for panel in fixture["panels"]:
        orbits = orbits_from_flat(panel["orbits"])
        fused_path = tmp_path / f"fused_{panel['name']}.csv"
        fallback_path = tmp_path / f"fallback_{panel['name']}.csv"
        orbits_to_sbdb_file(orbits, str(fused_path))
        _orbits_to_sbdb_file_legacy(orbits, str(fallback_path))
        assert fused_path.read_text() == fallback_path.read_text(), panel["name"]


def test_fused_csv_matches_legacy_fixture(fixture, tmp_path):
    for panel in fixture["panels"]:
        orbits = orbits_from_flat(panel["orbits"])
        path = tmp_path / f"{panel['name']}.csv"
        orbits_to_sbdb_file(orbits, str(path))
        assert_csv_matches_fixture(path.read_text(), panel["csv"], panel["name"])


def test_legacy_fallback_matches_legacy_fixture(fixture, tmp_path, monkeypatch):
    def _raise(*args, **kwargs):
        raise RuntimeError("forced legacy fallback")

    monkeypatch.setattr(_rust_native, "openspace_write_sbdb_csv", _raise)
    for panel in fixture["panels"]:
        orbits = orbits_from_flat(panel["orbits"])
        path = tmp_path / f"legacy_{panel['name']}.csv"
        orbits_to_sbdb_file(orbits, str(path))
        assert_csv_matches_fixture(path.read_text(), panel["csv"], panel["name"])


def test_python_float_repr_matches_python(fixture):
    for entry in fixture["float_repr_oracle"]:
        value = float.fromhex(entry["value_hex"])
        assert _rust_native.python_float_repr(value) == entry["repr"], entry


def test_fused_csv_native_timing(fixture, tmp_path):
    orbits = orbits_from_flat(fixture["panels"][0]["orbits"])
    samples = _rust_native.benchmark_openspace_write_sbdb_csv(
        str(tmp_path / "timing.csv"), orbits_to_ipc(orbits), 2, 2, 1
    )
    assert all(sample > 0.0 for trial in samples for sample in trial)
