"""Whole-product parity for OpenSpace asset creators (personal-cmy.37.4.5).

The frozen fixture is generated by the untouched pinned legacy checkout with
``.legacy-venv/bin/python migration/scripts/generate_openspace_asset_fixture.py``.
Fused outputs are byte-identical to the retained current compatibility
composition. Frozen-legacy text structure is exact; transform-derived numeric
tokens use the governed coordinate-transform tolerance because the Rust
trigonometric path can differ from legacy JAX/CSPICE by final ULPs.
"""

import json
import math
import re
from pathlib import Path

import pytest

from adam_core import _rust_native
from adam_core.coordinates import CartesianCoordinates
from adam_core.coordinates.origin import Origin
from adam_core.orbits import Orbits
from adam_core.orbits.arrow_bridge import orbits_to_ipc
from adam_core.orbits.openspace.assets import (
    create_renderable_orbital_kepler,
    create_renderable_trail_orbit,
)
from adam_core.time import Timestamp

FIXTURE_PATH = (
    Path(__file__).resolve().parents[5]
    / "migration"
    / "artifacts"
    / "openspace_asset_fixture_2026-07-12.json"
)
FLOAT_TOKEN = re.compile(r"(?<![A-Za-z_])[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?")


@pytest.fixture(scope="module")
def fixture():
    assert FIXTURE_PATH.exists(), (
        "OpenSpace asset product fixture missing; generate it with: "
        ".legacy-venv/bin/python "
        "migration/scripts/generate_openspace_asset_fixture.py"
    )
    return json.loads(FIXTURE_PATH.read_text())


def orbits_from_flat(flat: dict) -> Orbits:
    return Orbits.from_kwargs(
        orbit_id=flat["orbit_id"],
        object_id=flat["object_id"],
        coordinates=CartesianCoordinates.from_kwargs(
            x=flat["x"],
            y=flat["y"],
            z=flat["z"],
            vx=flat["vx"],
            vy=flat["vy"],
            vz=flat["vz"],
            time=Timestamp.from_kwargs(
                days=flat["days"], nanos=flat["nanos"], scale=flat["scale"]
            ),
            frame=flat["frame"],
            origin=Origin.from_kwargs(code=flat["origin"]),
        ),
    )


def run_case(case: dict, orbits: Orbits, root: Path) -> Path:
    out_dir = root / case["name"]
    kwargs = dict(case["kwargs"])
    # JSON has no tuple type; restore the tuple-valued public arguments used by
    # the legacy fixture generator.
    kwargs["color"] = tuple(kwargs["color"])
    if kwargs.get("outline_color") is not None:
        kwargs["outline_color"] = tuple(kwargs["outline_color"])
    if case["name"] == "trail_spice_resource":
        # Mirror fixture layout: <root>/trail_spice and <root>/kernels.
        out_dir = root / "trail_spice"
        kwargs["spice_kernel_path"] = str(root / "kernels" / "fixture kernel.bsp")
    if case["kind"] == "orbital_kepler":
        create_renderable_orbital_kepler(
            orbits, str(out_dir), case["identifier"], **kwargs
        )
    else:
        create_renderable_trail_orbit(
            orbits, str(out_dir), case["identifier"], **kwargs
        )
    return out_dir


def directory_contents(path: Path) -> dict[str, str]:
    assert not list(path.glob("*.tmp")), "staged files must never remain published"
    return {
        item.name: item.read_text() for item in sorted(path.iterdir()) if item.is_file()
    }


def assert_numeric_text_close(actual: str, expected: str, label: str):
    actual_numbers = [float(value) for value in FLOAT_TOKEN.findall(actual)]
    expected_numbers = [float(value) for value in FLOAT_TOKEN.findall(expected)]
    actual_skeleton = FLOAT_TOKEN.sub("#", actual)
    expected_skeleton = FLOAT_TOKEN.sub("#", expected)
    assert actual_skeleton == expected_skeleton, label
    assert len(actual_numbers) == len(expected_numbers), label
    for index, (a, b) in enumerate(zip(actual_numbers, expected_numbers)):
        assert math.isclose(a, b, rel_tol=1e-9, abs_tol=1e-8), (
            label,
            index,
            a,
            b,
        )


def assert_frozen_legacy_product(actual: dict[str, str], case: dict):
    assert set(actual) == set(case["files"]), case["name"]
    for name, expected in case["files"].items():
        text = actual[name]
        if name.endswith(".asset") and case["kind"] == "orbital_kepler":
            # This asset contains only option/model values, no transform result.
            assert text == expected, (case["name"], name)
        else:
            assert_numeric_text_close(text, expected, f"{case['name']}:{name}")


def test_fused_products_match_frozen_legacy(fixture, tmp_path):
    orbits = orbits_from_flat(fixture["orbits"])
    for case in fixture["cases"]:
        out_dir = run_case(case, orbits, tmp_path / "fused")
        assert_frozen_legacy_product(directory_contents(out_dir), case)


@pytest.mark.parametrize(
    "native_name",
    [
        "openspace_create_orbital_kepler_product",
        "openspace_create_trail_orbit_product",
    ],
)
def test_fused_products_match_current_fallback_exactly(
    fixture, tmp_path, monkeypatch, native_name
):
    cases = [
        case
        for case in fixture["cases"]
        if (case["kind"] == "orbital_kepler")
        == (native_name == "openspace_create_orbital_kepler_product")
    ]
    orbits = orbits_from_flat(fixture["orbits"])
    fused_root = tmp_path / "fused"
    fused = {
        case["name"]: directory_contents(run_case(case, orbits, fused_root))
        for case in cases
    }

    def _raise(*args, **kwargs):
        raise RuntimeError("forced compatibility fallback")

    monkeypatch.setattr(_rust_native, native_name, _raise)
    fallback_root = tmp_path / "fallback"
    fallback = {
        case["name"]: directory_contents(run_case(case, orbits, fallback_root))
        for case in cases
    }
    assert fused == fallback


def test_spice_validation_and_mapping_errors_match_legacy(fixture, tmp_path):
    orbits = orbits_from_flat(fixture["orbits"])
    with pytest.raises(
        ValueError, match="Spice kernel path is required for Spice translation"
    ):
        create_renderable_trail_orbit(
            orbits,
            str(tmp_path / "missing_path"),
            "missing path",
            translation_type="Spice",
            spice_id_mappings={},
        )
    with pytest.raises(KeyError, match="Object Alpha"):
        create_renderable_trail_orbit(
            orbits,
            str(tmp_path / "missing_mapping"),
            "missing mapping",
            translation_type="Spice",
            spice_kernel_path=str(tmp_path / "x.bsp"),
            spice_id_mappings={},
        )


def test_asset_products_have_rust_owned_timing(fixture, tmp_path):
    orbits = orbits_from_flat(fixture["orbits"])
    ipc = orbits_to_ipc(orbits)
    orbital = fixture["cases"][0]
    orbital_config = {"identifier": orbital["identifier"], **orbital["kwargs"]}
    trail = fixture["cases"][1]
    trail_config = {"identifier": trail["identifier"], **trail["kwargs"]}
    samples = [
        _rust_native.benchmark_openspace_create_orbital_kepler_product(
            ipc,
            1,
            1,
            0,
            out_dir=str(tmp_path / "orbital"),
            config_json=json.dumps(orbital_config),
        ),
        _rust_native.benchmark_openspace_create_trail_orbit_product(
            ipc,
            1,
            1,
            0,
            out_dir=str(tmp_path / "trail"),
            config_json=json.dumps(trail_config),
        ),
    ]
    assert all(value > 0.0 for result in samples for trial in result for value in trial)
