name: Docker Cleanup

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest  # Specify the type of runner. Adjust as needed.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

    - name: Check Disk Space After Cleanup
      run: |
        df -h  # Displays disk space usage

    - name: Docker Cleanup
      run: |
        docker system prune -af  # This command removes all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes.

    - name: Check Disk Space After Cleanup
      run: |
        df -h  # Displays disk space usage
