name: Build Lint Test and Coverage

on:
  push:
    branches: [ main, "v*"]
  pull_request:
    branches: [ main, "v*"]

jobs:
  build-lint-test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        shell: bash -l {0}
    env:
      OORB_DATA: /tmp/oorb/data

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install openorb dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gfortran liblapack-dev
          wget  -P /tmp/ https://storage.googleapis.com/oorb-data/oorb_data.tar.gz
          mkdir -p /tmp/oorb/
          tar -xvf /tmp/oorb_data.tar.gz -C /tmp/oorb/      
      - name: Install Testing Dependencies
        run: |
          pip install pip --upgrade
          pip install ".[dev]"
      - name: Lint
        run: pdm run lint
      - name: Test with coverage
        run: pdm run coverage
      - name: Coverage report to coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          path-to-lcov: coverage.xml
